version: "3.9"

services:
  frontend:
    build: ./fitness-tracker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./fitness-tracker-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fitdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    # Removed host port mapping to avoid conflict
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
