name: Full Stack CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: nikhil07h07
  DOCKERHUB_PASSWORD: @Sreenikhil_07
  FRONTEND_IMAGE: fitness-tracker-frontend
  BACKEND_IMAGE: fitness-tracker-backend

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: ./fitness-tracker-frontend
        run: npm install

      - name: Fix Vite permissions
        working-directory: ./fitness-tracker-frontend
        run: chmod +x ./node_modules/.bin/vite

      - name: Build React frontend
        working-directory: ./fitness-tracker-frontend
        run: npx vite build --base=/fitness-tracker-frontend/

      - name: Build Docker image for frontend
        run: docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE }}:latest ./fitness-tracker-frontend

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Push frontend image
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE }}:latest

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17 and Maven
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build Spring Boot backend
        working-directory: ./fitness-tracker-backend
        run: mvn clean package -DskipTests

      - name: Build Docker image for backend
        run: docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE }}:latest ./fitness-tracker-backend

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Push backend image
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE }}:latest